### ISSUE TITLE
search-sample OBJ format models don't load textures.

### ISSUE THREAD

**Issue by manthrax** [googlevr/poly-sample-web#2]
When loading an OBJ format object with textures, the texture loads fail as they attempt to load from server, rather than the resources actual remote directory specified by its url.

A workaround/hack is to insert the following code in the loading code in search-sample->createImage, where the MTLLoader is created:

```javascript

var loader = new THREE.MTLLoader();

loader.setCrossOrigin(true);
for(var i=0;i<format.resources.length;i++){
	var resource = format.resources[i];
	if(resource.contentType.indexOf("image/")==0){
		var texPathEnd = resource.url.indexOf(resource.relativePath);
		if(texPathEnd!=-1){
			loader.setTexturePath(resource.url.slice(0,texPathEnd));
			break;
		}
	}
}
```

This hack finds the first image/* resource, subtracts the filename from the URL, then sets the MTLLoaders "texturePath" to that. MTLLoader uses this path in subsequent texture load attempts.
Note, this triggers cross origin request, which requires setting loader.setCrossOrigin(true);

-hth

**Comment by mrdoob** [comment]
Fixed. Thanks!

**Comment by mrdoob** [comment]
@ianmacgillivray this issue can be closed.
