### ISSUE TITLE
search-sample: texture downloaded but doesn't apply into mesh, shown as black.

### ISSUE THREAD

**Issue by Ben-Mack** [googlevr/poly-sample-web#7]
In search-sample, when load some models like: 

- Burger: https://poly.google.com/view/eke7qcu_FR2
- Fox: https://poly.google.com/view/10u8FYPC5Br

The result shown as black model without texture, but texture downloaded sucessfully, please see below screenshot:
![poly error](https://user-images.githubusercontent.com/6309393/37209247-2943039c-23d7-11e8-99aa-fba98c9002b0.PNG)

**Comment by Ben-Mack** [comment]
Dear @mrdoob  

Have you found any feasible solution for this problem yet? 

There are quite a lot models with texture got into this problem ( even these models published by the original `Poly by Google` ).

**Comment by mrdoob** [comment]
I've not been able to investigate this yet. Hoping to have a look tomorrow.

**Comment by mrdoob** [comment]
```
newmtl Hamburguer_Mat
illum 4
Kd 0.00 0.00 0.00
Ka 0.00 0.00 0.00
Tf 1.00 1.00 1.00
map_Kd Hamburger_BaseColor.png
Ni 1.00
```

```
newmtl Fox_Mat
illum 4
Kd 0.00 0.00 0.00
Ka 0.00 0.00 0.00
Tf 1.00 1.00 1.00
map_Kd Fox_BaseColor.png
Ni 1.00
```

These are difficult mtl files. `Kd 0.00 0.00 0.00` ends up in `material.color.setRGB( 0, 0, 0 )` in three.js. So the texture is there, but the material color is multiplying it to 0.

I don't know if `MTLLoader` can be improved... I'm hoping Poly will add GLTF2 support and these kind of issues will go away.

Until then, you can do this:

```js
scene.traverse( function ( child ) {

    if ( child.material === undefined ) return;
    if ( child.material.color.getHex() === 0 ) child.material.color.setRGB( 1, 1, 1 );

} );

**Comment by Ben-Mack** [comment]
Thanks! I tried `ignoreZeroRGBs` options in MTLLoader and it works too 😄

**Comment by mrdoob** [comment]
> Thanks! I tried `ignoreZeroRGBs` options in MTLLoader and it works too 😄 

Oh! Hah! I forgot `MTLLoader` had that option.

**Comment by mrdoob** [comment]
Fixed. Thanks!
